import SwiftUI

/// Presentation-only prototype for the EsseLinea dashboard.
///
/// This view deliberately does not replace `MainChartView` yet. It accepts already-normalized
/// metabolic pressure values so that the visual language can be validated before connecting it
/// to dosing data or changing any APS behaviour.
struct MetabolicBalancePoint: Identifiable, Equatable {
    let id = UUID()
    let date: Date
    /// 0...1. Positive glucose pressure generated by active carbohydrates.
    let carbPressure: Double
    /// 0...1. Negative glucose pressure generated by active insulin.
    let insulinPressure: Double

    var balance: Double {
        min(max(carbPressure - insulinPressure, -1), 1)
    }
}

struct MetabolicBalanceChartView: View {
    let points: [MetabolicBalancePoint]
    let now: Date

    @Environment(\.colorScheme) private var colorScheme

    private let horizontalPadding: CGFloat = 18
    private let verticalPadding: CGFloat = 22
    private let dmzHeight: CGFloat = 7

    var body: some View {
        GeometryReader { proxy in
            let plotRect = CGRect(
                x: horizontalPadding,
                y: verticalPadding,
                width: max(proxy.size.width - horizontalPadding * 2, 1),
                height: max(proxy.size.height - verticalPadding * 2, 1)
            )
            let centerY = plotRect.midY

            ZStack {
                chartBackground

                if points.count > 1 {
                    carbArea(in: plotRect, centerY: centerY)
                        .fill(carbGradient)

                    insulinArea(in: plotRect, centerY: centerY)
                        .fill(insulinGradient)

                    dmzPath(in: plotRect, centerY: centerY)
                        .stroke(
                            dmzGradient,
                            style: StrokeStyle(lineWidth: dmzHeight, lineCap: .round, lineJoin: .round)
                        )
                        .shadow(color: dmzGlowColor.opacity(0.45), radius: 5)

                    nowMarker(in: plotRect)
                    labels(in: plotRect, centerY: centerY)
                } else {
                    Text("Metabolic Balance")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(.secondary)
                }
            }
            .clipShape(RoundedRectangle(cornerRadius: 22, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: 22, style: .continuous)
                    .stroke(borderColor, lineWidth: 1)
            }
        }
        .frame(minHeight: 260)
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(accessibilitySummary)
    }

    private var chartBackground: some View {
        RoundedRectangle(cornerRadius: 22, style: .continuous)
            .fill(colorScheme == .dark ? Color.black : Color.white)
    }

    private var borderColor: Color {
        colorScheme == .dark ? Color.white.opacity(0.12) : Color.black.opacity(0.08)
    }

    private var carbGradient: LinearGradient {
        LinearGradient(
            colors: [Color.orange.opacity(0.75), Color.orange.opacity(0.08)],
            startPoint: .top,
            endPoint: .bottom
        )
    }

    private var insulinGradient: LinearGradient {
        LinearGradient(
            colors: [Color.blue.opacity(0.08), Color.blue.opacity(0.78)],
            startPoint: .top,
            endPoint: .bottom
        )
    }

    /// The thick central time line is the DMZ. Its colour continuously represents which force dominates.
    private var dmzGradient: LinearGradient {
        LinearGradient(
            gradient: Gradient(stops: gradientStops),
            startPoint: .leading,
            endPoint: .trailing
        )
    }

    private var gradientStops: [Gradient.Stop] {
        guard points.count > 1 else {
            return [
                .init(color: .white, location: 0),
                .init(color: .white, location: 1)
            ]
        }

        return points.enumerated().map { index, point in
            Gradient.Stop(
                color: balanceColor(point.balance),
                location: Double(index) / Double(points.count - 1)
            )
        }
    }

    private var currentBalance: Double {
        points.min(by: { abs($0.date.timeIntervalSince(now)) < abs($1.date.timeIntervalSince(now)) })?.balance ?? 0
    }

    private var dmzGlowColor: Color {
        balanceColor(currentBalance)
    }

    private func balanceColor(_ balance: Double) -> Color {
        let clamped = min(max(balance, -1), 1)
        if abs(clamped) < 0.08 {
            return colorScheme == .dark ? .white : Color.black.opacity(0.72)
        }

        let strength = 0.45 + abs(clamped) * 0.55
        return clamped > 0
            ? Color.orange.opacity(strength)
            : Color.blue.opacity(strength)
    }

    private func carbArea(in rect: CGRect, centerY: CGFloat) -> Path {
        areaPath(in: rect, centerY: centerY, values: points.map(\.carbPressure), direction: -1)
    }

    private func insulinArea(in rect: CGRect, centerY: CGFloat) -> Path {
        areaPath(in: rect, centerY: centerY, values: points.map(\.insulinPressure), direction: 1)
    }

    private func areaPath(in rect: CGRect, centerY: CGFloat, values: [Double], direction: CGFloat) -> Path {
        var path = Path()
        guard values.count > 1 else { return path }

        let halfHeight = rect.height * 0.38
        path.move(to: CGPoint(x: rect.minX, y: centerY))

        for index in values.indices {
            let progress = CGFloat(index) / CGFloat(values.count - 1)
            let x = rect.minX + rect.width * progress
            let normalized = CGFloat(min(max(values[index], 0), 1))
            let y = centerY + direction * halfHeight * normalized
            path.addLine(to: CGPoint(x: x, y: y))
        }

        path.addLine(to: CGPoint(x: rect.maxX, y: centerY))
        path.closeSubpath()
        return path
    }

    private func dmzPath(in rect: CGRect, centerY: CGFloat) -> Path {
        var path = Path()
        guard points.count > 1 else { return path }

        let deformation = rect.height * 0.055
        for index in points.indices {
            let progress = CGFloat(index) / CGFloat(points.count - 1)
            let x = rect.minX + rect.width * progress
            let y = centerY - CGFloat(points[index].balance) * deformation
            let position = CGPoint(x: x, y: y)

            if index == points.startIndex {
                path.move(to: position)
            } else {
                path.addLine(to: position)
            }
        }
        return path
    }

    @ViewBuilder private func nowMarker(in rect: CGRect) -> some View {
        if let location = xPosition(for: now, in: rect) {
            Path { path in
                path.move(to: CGPoint(x: location, y: rect.minY))
                path.addLine(to: CGPoint(x: location, y: rect.maxY))
            }
            .stroke(
                Color.secondary.opacity(0.75),
                style: StrokeStyle(lineWidth: 1, dash: [5, 5])
            )

            Circle()
                .fill(colorScheme == .dark ? Color.white : Color.black)
                .frame(width: 8, height: 8)
                .position(x: location, y: rect.midY)
        }
    }

    private func labels(in rect: CGRect, centerY: CGFloat) -> some View {
        ZStack {
            Text("CARBS")
                .font(.caption2.weight(.semibold))
                .foregroundStyle(Color.orange)
                .position(x: rect.minX + 24, y: rect.minY + 10)

            Text("INSULIN")
                .font(.caption2.weight(.semibold))
                .foregroundStyle(Color.blue)
                .position(x: rect.minX + 28, y: rect.maxY - 10)

            Text("BALANCE")
                .font(.caption2.weight(.medium))
                .foregroundStyle(.secondary)
                .position(x: rect.maxX - 32, y: centerY - 16)
        }
    }

    private func xPosition(for date: Date, in rect: CGRect) -> CGFloat? {
        guard let first = points.first?.date, let last = points.last?.date, last > first else { return nil }
        let progress = date.timeIntervalSince(first) / last.timeIntervalSince(first)
        return rect.minX + rect.width * CGFloat(min(max(progress, 0), 1))
    }

    private var accessibilitySummary: String {
        if currentBalance > 0.08 {
            return NSLocalizedString("Metabolic balance: carbohydrates dominant", comment: "")
        }
        if currentBalance < -0.08 {
            return NSLocalizedString("Metabolic balance: insulin dominant", comment: "")
        }
        return NSLocalizedString("Metabolic balance: balanced", comment: "")
    }
}

#if DEBUG
struct MetabolicBalanceChartView_Previews: PreviewProvider {
    static var previews: some View {
        let start = Date().addingTimeInterval(-3 * 60 * 60)
        let points = (0 ... 12).map { index in
            let progress = Double(index) / 12
            return MetabolicBalancePoint(
                date: start.addingTimeInterval(Double(index) * 30 * 60),
                carbPressure: max(0, sin(progress * .pi) * 0.8),
                insulinPressure: max(0, sin((progress + 0.18) * .pi) * 0.72)
            )
        }

        return MetabolicBalanceChartView(points: points, now: Date())
            .padding()
            .preferredColorScheme(.dark)
    }
}
#endif
